# Generated by Django 3.0.7 on 2020-06-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=180)),
                ('short_desc', models.TextField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='explores')),
            ],
        ),
    ]
