# Generated by Django 3.0.7 on 2020-06-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_post_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.RenameField(
            model_name='explores',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='explores',
            name='image_10',
            field=models.ImageField(blank=True, upload_to='explores'),
        ),
        migrations.AddField(
            model_name='explores',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='explores'),
        ),
        migrations.AddField(
            model_name='explores',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='explores'),
        ),
        migrations.AddField(
            model_name='explores',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='explores'),
        ),
        migrations.AddField(
            model_name='explores',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='explores'),
        ),
        migrations.AddField(
            model_name='explores',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='explores'),
        ),
        migrations.AddField(
            model_name='explores',
            name='image_7',
            field=models.ImageField(blank=True, upload_to='explores'),
        ),
        migrations.AddField(
            model_name='explores',
            name='image_8',
            field=models.ImageField(blank=True, upload_to='explores'),
        ),
        migrations.AddField(
            model_name='explores',
            name='image_9',
            field=models.ImageField(blank=True, upload_to='explores'),
        ),
        migrations.AddField(
            model_name='explores',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='explores'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
