# Generated by Django 3.0.7 on 2020-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_auto_20200614_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='explores',
            name='google_map_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='explores',
            name='google_map_link',
            field=models.TextField(blank=True),
        ),
    ]
