# Generated by Django 3.0.7 on 2020-06-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_auto_20200614_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='explores',
            name='rank',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
