# Generated by Django 3.0.7 on 2020-06-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_explores_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='explores',
            name='distance',
            field=models.TextField(blank=True),
        ),
    ]
