# Generated by Django 3.0.7 on 2020-06-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_explores_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explores',
            old_name='distance',
            new_name='dist_from_ckm',
        ),
        migrations.AddField(
            model_name='explores',
            name='dist_from_mys',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='explores',
            name='distance_from_bang',
            field=models.TextField(blank=True),
        ),
    ]
