# Generated by Django 3.0.7 on 2020-06-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0008_auto_20200614_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='explores',
            name='facebook_link_thumbnail',
            field=models.TextField(blank=True),
        ),
    ]
