# Generated by Django 3.0.7 on 2020-06-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0009_explores_facebook_link_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veg_or_Nonveg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('google_link', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('google_map_html', models.TextField()),
                ('type_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_hotel', to='basicapp.Veg_or_Nonveg')),
            ],
        ),
    ]
