# Generated by Django 3.0.7 on 2020-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0010_hotels_veg_or_nonveg'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='rank',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
