# Generated by Django 3.0.7 on 2020-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0011_hotels_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='google_rating',
            field=models.TextField(default=3, max_length=5),
            preserve_default=False,
        ),
    ]
