# Generated by Django 3.0.7 on 2020-06-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0012_hotels_google_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='google_rating',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='veg_or_nonveg',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
