# Generated by Django 3.0.7 on 2020-06-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0014_hotels_veg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='type_hotel',
        ),
        migrations.DeleteModel(
            name='Veg_or_Nonveg',
        ),
    ]
