# Generated by Django 3.0.7 on 2020-06-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0015_auto_20200618_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='explores',
            name='three_view',
            field=models.TextField(blank=True),
        ),
    ]
