# Generated by Django 3.0.7 on 2020-06-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0016_explores_three_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homestays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rank', models.PositiveIntegerField()),
                ('desc', models.TextField()),
                ('price_range', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('level', models.TextField()),
                ('google_map_link', models.TextField()),
                ('rating', models.TextField()),
            ],
        ),
    ]
