# Generated by Django 3.0.7 on 2020-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0017_homestays'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestays',
            name='google_map_html',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
