# Generated by Django 3.0.7 on 2020-06-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0018_homestays_google_map_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homestays',
            old_name='rating',
            new_name='google_rating',
        ),
    ]
