# Generated by Django 3.0.7 on 2020-06-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0019_auto_20200621_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestays',
            name='premium',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
