# Generated by Django 3.0.7 on 2020-06-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0021_auto_20200621_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malnadspecials',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='homestays'),
        ),
    ]
